# Generated by Django 3.2.5 on 2021-07-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarGasData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles_driven', models.FloatField()),
                ('gallons_used', models.FloatField()),
                ('mpg', models.FloatField()),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_data', to='cars.car')),
            ],
        ),
    ]
