# Generated by Django 3.2.5 on 2021-07-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cargasdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
